# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='Discriptions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
