# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0004_auto_20180808_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
