# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0006_contents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='user_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
