# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0007_auto_20180816_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
