# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0008_auto_20180816_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='details',
        ),
        migrations.AddField(
            model_name='contents',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
