# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0009_auto_20180817_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='image',
        ),
        migrations.AddField(
            model_name='contents',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
