# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0010_auto_20180817_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
