# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bored', '0012_auto_20180821_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['-timestamp']},
        ),
    ]
